name: randomneet
on: [push]

jobs:
    randomneet:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.5, 3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: "Upgrade pip"
              run: python -m pip install --upgrade pip
            - name: "Install dependencies"
              run: |
                  python -m pip install lxml codecov green flake8
                  python -m pip install neet==1.0.0
                  python -m pip install .
            - name: "Run tests"
              run: green
            - name: "Submit test coverage"
              run: codecov
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            - name: "Lint"
              run: flake8
