name: randomneet
on: [push]

jobs:
    randomneet:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2
            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
            - name: "Upgrade pip"
              run: python -m pip install --upgrade pip
            - name: "Install dependencies"
              run: | 
                  pip install .
                  pip install codecov
            - name: "Lint"
              run: flake8
            - name: "Run tests"
              run: python setup.py test
            - name: "Submit test coverage"
              run: codecov
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
